Administration_page_optimizations
igrigorov/spring-react-i18n-admin pull request #20
Opened 2021-05-13 11:23 UTC by karabidas13

First need to accept the "Edit localization entry #6" and then this request

2021-05-14 08:22 UTC, igrigorov requested changes
- Regarding column width: the maths looks good in the code, but the result is far from there:
![colPercent](https://user-images.githubusercontent.com/975552/118242423-fe100b80-b4a5-11eb-88bc-9bf58353c224.png)
- In addition, the textboxes are far smaller than the column width - make them as wide as the column is, with some small padding, say 5-10px
![textboxWidth](https://user-images.githubusercontent.com/975552/118242784-5ba45800-b4a6-11eb-862e-be6d6c199128.png)

2021-05-14 12:54 UTC, karabidas13 commented
WARNING!!!!!!Dont you dare erase the width: null you ll destroy everything!!!!!!

2021-05-14 13:47 UTC, igrigorov requested changes
* Column percentage is black magic... in the good sense 👌 
* Language text fields (EN/BG) have not been fixed

2021-05-18 08:22 UTC, igrigorov approved these changes

2021-05-18 08:22 UTC, merged